import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { ProgramsService } from '../../services/programs.service';
import { User } from '../../models/Users';
import { dA } from '@fullcalendar/core/internal-common';
import { Services } from '../../models/Services';
import {
  FormBuilder,
  FormGroup,
  FormsModule,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { ScheduleService } from '../../services/schedule.service';
import { ActivatedRoute, Router } from '@angular/router';
import { Schedule } from '../../models/Schedule';
import { AppointmentService } from '../../services/appointment.service';
import { CommonModule } from '@angular/common';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { AppointmentPreviewComponent } from './appointment-preview/appointment-preview.component';
import { Appointment, AppointmentStatus } from '../../models/Appointment';
import Swal from 'sweetalert2';
import { Survey } from '../../models/Survey';
import { SurveyComponent } from '../../user/survey/survey.component';
import { SurveyService } from '../../services/survey.service';

@Component({
  selector: 'app-create-appointment',
  standalone: true,
  imports: [ReactiveFormsModule, FormsModule, CommonModule],
  templateUrl: './create-appointment.component.html',
  styleUrl: './create-appointment.component.scss',
})
export class CreateAppointmentComponent implements OnInit {
  user$: User | null = null;
  services$: Services[] = [];
  appointmentForm: FormGroup;
  selectedServiceId: string | null = null;
  schedules: Schedule[] = [];
  isGettingSchedules = false;
  selectedSchedule: Schedule | null = null;
  hasPendingAppointment = false;
  constructor(
    private authService: AuthService,
    private programService: ProgramsService,
    private fb: FormBuilder,
    private scheduleService: ScheduleService,
    private activatedRoute: ActivatedRoute,
    private modalService: NgbModal,
    private surveyService: SurveyService,
    private appointmentService: AppointmentService, // assumed service for saving appointments
    private router: Router // for navigation after submission
  ) {
    this.appointmentForm = fb.nonNullable.group({
      name: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      contact: ['', Validators.required],
      serviceId: ['', Validators.required],
      date: ['', Validators.required],
    });
  }

  // Triggered when serviceId and date change
  onServiceAndDateChanged(serviceId: string, date: string) {
    this.isGettingSchedules = true;
    this.scheduleService
      .getScheduleByDate(serviceId, date)
      .then((data) => {
        this.isGettingSchedules = false;
        this.schedules = data;
        this.onSelectSchedule(null);
      })
      .catch((e) => {
        console.log(e);
      });
  }
  onSelectSchedule(schedule: Schedule | null) {
    this.selectedSchedule = schedule;
  }

  ngOnInit(): void {
    this.activatedRoute.queryParamMap.subscribe((param) => {
      this.selectedServiceId = param.get('id');
      if (this.selectedServiceId) {
        this.appointmentForm.patchValue({ serviceId: this.selectedServiceId });
      }
    });

    this.authService.getCurrentUser().subscribe((data) => {
      this.user$ = data;
      if (data) {
        this.appointmentForm.patchValue({
          name: data.name,
          email: data.email,
        });

        this.appointmentService.hasPendingAppointment(data.id).then((data) => {
          this.hasPendingAppointment = data;
        });
      }
    });

    this.programService.getAll().subscribe((data) => {
      this.services$ = data;
    });
  }

  minDate = new Date().toISOString().split('T')[0]; // disables past dates

  trackByIndex(index: number): number {
    return index;
  }

  submit() {
    if (this.appointmentForm.invalid || !this.selectedSchedule) {
      Swal.fire({
        icon: 'warning',
        title: 'Incomplete Form',
        text: 'Please fill out all required fields and select a schedule.',
      });
      return;
    }
    const form = this.appointmentForm.value;
    const appointment: Appointment = {
      id: '', // to be generated by backend
      uid: this.user$?.id || '',
      sid: this.selectedSchedule.id,
      personalInformation: {
        name: form.name,
        email: form.email,
        contact: form.contact,
      },
      serviceInformation: {
        id:
          this.services$.find((s) => s.id === form.serviceId)?.id ||
          form.serviceId,
        name:
          this.services$.find((s) => s.id === form.serviceId)?.title ||
          'Unknown Service',
      },
      date: form.date,
      time: this.selectedSchedule.time,
      location: 'Sitio Agsuli, Sto. Nino, Sablayan, Occidental Mindoro',
      status: AppointmentStatus.PENDING,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    const modalRef = this.modalService.open(AppointmentPreviewComponent);
    modalRef.componentInstance.appointment = appointment;
    modalRef.result.then((data) => {
      if (data === true) {
        this.openSurvey();
      }
    });
  }

  openSurvey() {
    const modalRef = this.modalService.open(SurveyComponent);
    modalRef.result
      .then((result: Survey | any) => {
        if (result) {
          result.uid = this.user$?.id;
          result.profile = this.user$?.profile;
          result.name = this.user$?.name;
          this.saveSurvey(result);
        }
      })
      .catch((error) => {
        console.log('Survey modal dismissed:', error);
      });
  }

  saveSurvey(survey: Survey) {
    this.surveyService
      .create(survey)
      .then(() => {
        Swal.fire({
          icon: 'success',
          title: 'Survey Submitted',
          text: 'Thank you for completing the survey!',
          confirmButtonColor: '#3085d6',
        });
      })
      .catch((error) => {
        Swal.fire({
          icon: 'error',
          title: 'Submission Failed',
          text: 'Something went wrong. Please try again later.',
          confirmButtonColor: '#d33',
        });
        console.error('Survey submission error:', error);
      });
  }
}
